# Generated by Django 4.2.7 on 2023-11-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_lawyer_name_alter_lawyer_bio_alter_lawyer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
